### PR TITLE
Sto 19 add world loading

### PR DESCRIPTION
**Pull request by Nuckerr**

### CODE REVIEW

**Comment by Nuckerr** [comment]
@SimplyMerlin 
So this code needs to run, however name is null, and therefore they cant load
https://github.com/StomMiniGames/StomMiniGames/blob/a77a7b5db9a682b706405c9d5ed01a337667d05e/src/main/kotlin/com/simplymerlin/minigameserver/core/Minigame.kt#L21-L28

**Comment by Nuckerr** [comment]
There is one really big issue with this, once the game ends, it will just be the same map again

**Comment by Nuckerr** [comment]
Also, I had to turn name into a constructor variable, review please

**Review by SimplyMerlin — APPROVED** [review]

**Comment by SimplyMerlin** [comment]
ty <3

**Pull request merged**
